BEGIN;
REVOKE ALL ON FUNCTION public.approve_mp_pix_sale(uuid,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.cancel_mp_pix_sale(uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.approve_mp_pix_sale(uuid,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.cancel_mp_pix_sale(uuid) TO service_role;
REVOKE ALL ON FUNCTION public.get_profitability_by_category(date,date) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.get_profitability_by_product(date,date) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.report_inventory_movements_summary(timestamptz,timestamptz) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.report_stock_status() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.report_top_selling_products(integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_profitability_by_category(date,date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_profitability_by_product(date,date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.report_inventory_movements_summary(timestamptz,timestamptz) TO authenticated;
GRANT EXECUTE ON FUNCTION public.report_stock_status() TO authenticated;
GRANT EXECUTE ON FUNCTION public.report_top_selling_products(integer) TO authenticated;
REVOKE ALL ON FUNCTION public.get_user_store_role(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.has_store_access(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.rls_auto_enable() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.manage_product(uuid,text,text,text,numeric,numeric,jsonb) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.approve_physical_inventory(uuid,uuid) FROM PUBLIC, anon;
CREATE INDEX IF NOT EXISTS idx_inventory_movements_user_id ON public.inventory_movements(user_id);
CREATE INDEX IF NOT EXISTS idx_physical_inventories_approved_by ON public.physical_inventories(approved_by);
CREATE INDEX IF NOT EXISTS idx_physical_inventories_created_by ON public.physical_inventories(created_by);
CREATE INDEX IF NOT EXISTS idx_physical_inventories_store_id ON public.physical_inventories(store_id);
CREATE INDEX IF NOT EXISTS idx_physical_inventory_items_inventory_id ON public.physical_inventory_items(inventory_id);
CREATE INDEX IF NOT EXISTS idx_physical_inventory_items_product_variant_id ON public.physical_inventory_items(product_variant_id);
CREATE INDEX IF NOT EXISTS idx_return_items_product_id ON public.return_items(product_id);
CREATE INDEX IF NOT EXISTS idx_returns_created_by ON public.returns(created_by);
CREATE INDEX IF NOT EXISTS idx_returns_customer_id ON public.returns(customer_id);
CREATE INDEX IF NOT EXISTS idx_sale_idempotency_sale_id ON public.sale_idempotency(sale_id);
CREATE INDEX IF NOT EXISTS idx_sale_items_product_id ON public.sale_items(product_id);
CREATE INDEX IF NOT EXISTS idx_sales_user_id ON public.sales(user_id);
COMMIT;